/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf8fe',
        'surface-dim': '#dad9df',
        'surface-bright': '#faf8fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'on-surface': '#1a1b1f',
        'on-surface-variant': '#404752',
        'inverse-surface': '#2f3034',
        'inverse-on-surface': '#f1f0f5',
        outline: '#717783',
        'outline-variant': '#c0c7d4',
        'surface-tint': '#0060ab',
        primary: '#005faa',
        'on-primary': '#ffffff',
        'primary-container': '#0078d4',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#a3c9ff',
        secondary: '#5c5f60',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee0e2',
        'on-secondary-container': '#606365',
        tertiary: '#5e5d60',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#777678',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d3e3ff',
        'primary-fixed-dim': '#a3c9ff',
        'on-primary-fixed': '#001c39',
        'on-primary-fixed-variant': '#004883',
        'secondary-fixed': '#e1e2e4',
        'secondary-fixed-dim': '#c5c7c8',
        'on-secondary-fixed': '#191c1e',
        'on-secondary-fixed-variant': '#444749',
        'tertiary-fixed': '#e4e2e4',
        'tertiary-fixed-dim': '#c8c6c8',
        'on-tertiary-fixed': '#1b1b1d',
        'on-tertiary-fixed-variant': '#474649',
        background: '#faf8fe',
        'on-background': '#1a1b1f',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        unit: '8px',
        'container-max': '1200px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '24px',
        'section-gap': '120px',
      }
    },
  },
  plugins: [],
}
